### ISSUE TITLE
adding rlwrap

### ISSUE THREAD

**Issue by vans163** [bake-bake-bake/bakeware#101]
Using the up arrow key (on linux) in a release produced escape codes
![image](https://user-images.githubusercontent.com/3028982/111172731-7298fd80-857c-11eb-8b3e-fd9a8c521f58.png)

If running with rlwrap, the keys work fine.

Maybe we can also pack rlwrap into the binary, and make the runner call rlwrap ./mybakedapp

**Comment by fhunleth** [comment]
I think that there's something more going on here since arrows normally work with the `iex` prompt. I tried this outside of Bakeware in an OTP release and saw that arrow keys did not work there either. I'm using the Bakeware `iex_prompt` example for my testing.

It's been a while since I debugged Erlang I/O server issues, but this feels like `tty_sl` isn't running for some reason and we're using the old Erlang I/O server.

It's late, but I'm wondering if some googling or searching may find out why this is happening. I think that in the past, I had to instrument `IEx.CLI` to figure out what happened, so that would be my next attempt.

**Comment by fhunleth** [comment]
@vans163 Could you check out the `main` branch and try out the `iex_prompt` example now? I think that it will meet your needs and you won't need `rlwrap`. See https://github.com/bake-bake-bake/bakeware/pull/103 for the commits that updated the `iex_prompt` example.

**Comment by vans163** [comment]
This works great, no need for rlwrap.

**Comment by fhunleth** [comment]
Thanks for trying it out and letting us know!
