### ISSUE TITLE
Missing `release` in `assembler` struct during bakeware.assemble

### ISSUE THREAD

**Issue by christhekeele** [bake-bake-bake/bakeware#98]
Hey there!

I'm getting this error when trying to run the `mix bakeware.assemble` task:

`(UndefinedFunctionError) function nil.options/0 is undefined.`

Stack trace points to this line: https://github.com/bake-bake-bake/bakeware/blob/fb177b6c376d8fbf3502573fa7285cc2485440a2/lib/bakeware/assembler.ex#L154

I think it's possible I'm hitting [this entrypoint](https://github.com/bake-bake-bake/bakeware/blob/fb177b6c376d8fbf3502573fa7285cc2485440a2/lib/bakeware/assembler.ex#L43) instead of [this one](https://github.com/bake-bake-bake/bakeware/blob/fb177b6c376d8fbf3502573fa7285cc2485440a2/lib/bakeware/assembler.ex#L34) that properly sets up the value of `release` in the `assembler` struct?

Reproduction repo here, with pinned erlang, elixir, and bakeware version numbers: https://github.com/christhekeele/bakeware_issue

Quite possible this is a user error, and I've missed something from the documentation? Am I missing a required flag or config option somewhere? Thanks for any help!

**Comment by jjcarstens** [comment]
Thanks @christhekeele!

So this is interesting and what you've actually pointed out is a long lost mix task that I believe was mainly used in the heat of spawnfest when first developing this. However, I don't think it will actually work now because it does not compile in the release so it can't actually run the app.

`mix bakeware.assemble` needs to be reevaluated. In the interim, you can just use `mix release` to compile everything into the executable and copy it from `_build/{MIX_ENV}/rel/bakeware/{APP_NAME}`

**Comment by christhekeele** [comment]
Makes sense to me! Want me to PR removing it from the documentation @jjcarstens?
